version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    container_name: elasticsearch
    environment:
    - discovery.type=single-node
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    volumes:
    - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
    - "9200:9200"
    - "9300:9300"
    networks:
    - elk
  logstash:
    image: docker.elastic.co/logstash/logstash:6.5.1
    ports:
    - "5000:5000"
    - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
    - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
    - elk
    depends_on:
    - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.1
    ports:
    - "5601:5601"
    volumes:
    - ./kibana/config/:/usr/share/kibana/config
    networks:
    - elk
    depends_on:
    - elasticsearch

networks:
  elk:
    driver: bridge